# Strings

In [7]:
using Pkg
Pkg.add("JupyterFormatter")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`


In [8]:
using JupyterFormatter
enable_autoformat()

2-element Vector{Function}:
 format_current_cell (generic function with 1 method)
 format_current_cell (generic function with 1 method)

In [10]:
split("hello world")

2-element Vector{SubString{String}}:
 "hello"
 "world"

In [11]:
join(["hello", "world"], ' ')

"hello world"

In [12]:
replace("hello world", "world" => "john")

"hello john"

In [13]:
strip(" hello world ")

"hello world"

In [14]:
string("hello", "world")

"helloworld"

In [15]:
"hello" * "world"

"helloworld"

In [16]:
str1 = "hello"
str2 = "world"
"$str1 $str2"

"hello world"

# Array

In [17]:
a = Int64[]

Int64[]

In [19]:
# One-dimensional array.
a = Array{Int64,1}()

Int64[]

In [23]:
zeros(Int64, 5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [24]:
ones(Int64, 5)

5-element Vector{Int64}:
 1
 1
 1
 1
 1

In [25]:
a = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [27]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [28]:
a = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [29]:
a = [1 2; 2 3; 3 4]

3×2 Matrix{Int64}:
 1  2
 2  3
 3  4

In [30]:
# Use union for heterogeneous array for better performance.
a = Union{Int64,String,Bool}[10, "Foo", false]

3-element Vector{Union{Bool, Int64, String}}:
    10
      "Foo"
 false

In [31]:
a = [10, "Foo", false]

3-element Vector{Any}:
    10
      "Foo"
 false

In [33]:
a = collect(0:2:10)

6-element Vector{Int64}:
  0
  2
  4
  6
  8
 10

In [34]:
a = collect(0:10)

11-element Vector{Int64}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [38]:
a = vcat(0, 5:10, 20)

8-element Vector{Int64}:
  0
  5
  6
  7
  8
  9
 10
 20

In [39]:
a = [0; 5:10; 20]

8-element Vector{Int64}:
  0
  5
  6
  7
  8
  9
 10
 20

In [40]:
# Without semicolon, it has a different meaning.
a = [0, 5:10, 20]

3-element Vector{Any}:
  0
   5:10
 20

In [56]:
a = Array{Int64,1}()
b = [3, 4, 5]
print(a)

# Push adds item(s) to an array.
push!(a, 1, 2)

# Append an array b to a.
append!(a, b)
append!(a, 10)
print(a)

Int64[][1, 2, 3, 4, 5, 10]

In [57]:
sort(vcat(a, b))

9-element Vector{Int64}:
  1
  2
  3
  3
  4
  4
  5
  5
 10

In [58]:
pop!(a)

10

In [59]:
popfirst!(a)

1

In [60]:
a

4-element Vector{Int64}:
 2
 3
 4
 5

In [68]:
pushfirst!(a, -1)
push!(a, -20)

7-element Vector{Int64}:
  -1
  -1
   2
   3
   4
   5
 -20

In [69]:
print(sort(a)) # Returns a new array.
a

[-20, -1, -1, 2, 3, 4, 5]

7-element Vector{Int64}:
  -1
  -1
   2
   3
   4
   5
 -20

In [71]:
sort!(a) # Modifies an array.
a

7-element Vector{Int64}:
 -20
  -1
  -1
   2
   3
   4
   5

In [72]:
# Reversing an array.
a[end:-1:1]

7-element Vector{Int64}:
   5
   4
   3
   2
  -1
  -1
 -20

In [73]:
in(1, a)

false

In [74]:
in(-1, a)

true

In [75]:
length(a)

7

In [77]:
maximum(a), minimum(a)

(5, -20)

In [78]:
max(a...)

5

In [79]:
min(a...)

-20

In [80]:
empty!(a)

Int64[]

In [82]:
# Transform row vector in column vectors.
a = [1, 2, 3, 4, 5]
print(a)
b = vec(a)

[1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [83]:
a = [1 2; 3 4]
print(a)
b = vec(a)

[1 2; 3 4]

4-element Vector{Int64}:
 1
 3
 2
 4

In [88]:
using Random

shuffle!(b)

4-element Vector{Int64}:
 2
 1
 3
 4

In [89]:
shuffle(b)

4-element Vector{Int64}:
 1
 4
 2
 3

In [90]:
findall(x -> x > 2, b)

2-element Vector{Int64}:
 3
 4

In [93]:
map((a, b) -> a + b, [1, 2, 3], [4, 5])

2-element Vector{Int64}:
 5
 7

In [94]:
a = [[1, 2, 3], [4, 5, 6]]

2-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]

In [95]:
a = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [96]:
hcat([1, 2, 3], [4, 5, 6])

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

In [97]:
vcat([1, 2, 3], [4, 5, 6])

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [98]:
zeros(2, 3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [99]:
zeros(Int64, 2, 3)

2×3 Matrix{Int64}:
 0  0  0
 0  0  0

In [100]:
fill("abc", 2, 3)

2×3 Matrix{String}:
 "abc"  "abc"  "abc"
 "abc"  "abc"  "abc"

In [103]:
# Masking
a = [[1, 2, 3] [4, 5, 6]]
mask = [[true, false, false] [false, true, false]]
a[mask]

2-element Vector{Int64}:
 1
 5

In [105]:
a = [1, 2, 3]
mask = [true, false, true]
a[mask]

2-element Vector{Int64}:
 1
 3

In [106]:
a[1]

1

In [110]:
size(a)

(3,)

In [111]:
ndims(a)

1

In [118]:
a = [1, 2, 3, 4]
b = reshape(a, 2, 2)

2×2 Matrix{Int64}:
 1  3
 2  4

In [119]:
b', transpose(b)

([1 2; 3 4], [1 2; 3 4])

In [120]:
permutedims(b)

2×2 Matrix{Int64}:
 1  2
 3  4

# Tuples

In [121]:
a = (1, 2, 3)
b = 1, 2, 3
a, b

((1, 2, 3), (1, 2, 3))

In [122]:
# Convert tuple to vector
v = [a...]

3-element Vector{Int64}:
 1
 2
 3

In [123]:
v = [i[1] for i in a]

3-element Vector{Int64}:
 1
 2
 3

In [124]:
v = collect(a)

3-element Vector{Int64}:
 1
 2
 3

# Named Tuples

In [125]:
a = (a = 1, b = 2)

(a = 1, b = 2)

In [127]:
a[:a], a[:b]

(1, 2)

In [128]:
# Get a tuple of the keys.
keys(a)

(:a, :b)

In [129]:
# Get a tuple of the values.
values(a)

(1, 2)

In [130]:
# Get an array of the values.
collect(a)

2-element Vector{Int64}:
 1
 2

In [133]:
for (k, v) in pairs(a)
    println(k, v)
end

a1
b2


# Dictionaries

In [134]:
a = Dict('a' => 1, 'b' => 2)

Dict{Char, Int64} with 2 entries:
  'a' => 1
  'b' => 2

In [135]:
a = Dict(:a => 1, :b => 2)

Dict{Symbol, Int64} with 2 entries:
  :a => 1
  :b => 2

In [136]:
a = Dict(a => 1, b => 2)

Dict{Any, Int64} with 2 entries:
  (1, 2, 3)          => 2
  Dict(:a=>1, :b=>2) => 1

In [140]:
d = Dict()
map((a, b) -> d[a] = b, [1, 2, 3], [10, 20, 30])
d

Dict{Any, Any} with 3 entries:
  2 => 20
  3 => 30
  1 => 10

In [141]:
d[1]

10

In [142]:
get(d, 1000, 0)

0

In [143]:
keys(d)

KeySet for a Dict{Any, Any} with 3 entries. Keys:
  2
  3
  1

In [144]:
values(d)

ValueIterator for a Dict{Any, Any} with 3 entries. Values:
  20
  30
  10

In [145]:
collect(d)

3-element Vector{Pair{Any, Any}}:
 2 => 20
 3 => 30
 1 => 10

In [147]:
haskey(d, 'a')

false

In [148]:
in((1 => 10), d)

true

In [149]:
for (k, v) in d
    println("$k is $v")
end

2 is 20
3 is 30
1 is 10


# Sets

In [150]:
a = Set()

Set{Any}()

In [151]:
a = Set([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [152]:
a = Set([1, 2, 3])
b = Set([2, 3, 4])

intersect(a, b)

Set{Int64} with 2 elements:
  2
  3

In [153]:
union(a, b)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [154]:
setdiff(a, b)

Set{Int64} with 1 element:
  1

In [155]:
setdiff(b, a)

Set{Int64} with 1 element:
  4